remove the trailing CR at the end of the cell
It would cause `eval()` to fail on an empty string with a
SyntaxError: unexpected EOF while parsing (<string>, line 0)